title: Vrindavan Mango Nectar
description: स्व्यंभू श्री राधारमण
ラダ・ラマナ
author: स्व्यंभू श्री राधारमण
email: yajnavalkya@live.com
lang: hi-in
copyright: "&#xA9; स्व्यंभू श्री राधारमण"
logo: /assets/img/rr5.png
url: "https://nacicatus.github.io" 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
